# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telenum',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
