# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_telenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='opencourse',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='exam',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='usual',
            field=models.FloatField(null=True),
        ),
    ]
