# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20170518_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='gpa',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
